### ISSUE TITLE
There is no link to follow for downloading the data

### ISSUE THREAD

**Issue by rahulbhadani** [NYSCF/monoqlo_release#1]
In the README, it is mentioned "An example dataset, consisting of a single plate, can be downloaded from the following link:"
but there is no link to follow.

Please, kindly provide data link that you were intended to include.

Thanks.

**Comment by brodie-brodes** [comment]
Hi - apologies for the slow delay. Looks like there was a typo. The section for downloading the test data is a little further down the readme, where a link and guide for downloading the test data are provided.

**Comment by brodie-brodes** [comment]
Hi - looks like there was a typo. The section for downloading the test data is a little further down the readme, where a link and guide for downloading the test data are provided.

**Comment by brodie-brodes** [comment]
The section for downloading the test data is a little further down the readme, where a link and guide for downloading the test data are provided.
